version: '3.7'
services:
    grafana:
        image: "grafana/grafana"
        hostname: "grafana"
        environment:
            GF_SECURITY_ADMIN_PASSWORD: "secret"
        ports:
            - "8084:3000"
        networks:
            - poc
        labels:
            NAME: "grafana"
networks:
    poc:
        external: true